[platformio]
default_envs = m5stack-sticks3

[env:m5stack-sticks3]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.partitions = default_8MB.csv
board_build.arduino.memory_type = qio_opi
monitor_speed = 115200
upload_port = /dev/cu.usbmodem*
monitor_port = /dev/cu.usbmodem*
upload_speed = 460800
lib_deps =
  M5Unified=https://github.com/m5stack/M5Unified
  M5PM1=https://github.com/m5stack/M5PM1
  h2zero/NimBLE-Arduino @ ^2.5.0
build_flags =
  -std=gnu++17
  -D BOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
  -D CORE_DEBUG_LEVEL=5
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D CONFIG_MBEDTLS_SSL_MAX_CONTENT_LEN=4096
  -D CONFIG_MBEDTLS_SSL_IN_CONTENT_LEN=4096
  -D CONFIG_MBEDTLS_SSL_OUT_CONTENT_LEN=4096

[env:native]
platform = native
test_framework = unity
build_flags =
  -std=gnu++17
