[env:m5stick-c]
platform = espressif32
board = m5stick-c
framework = arduino
board_build.partitions = partitions_2m_app_1920k_fs.csv
monitor_speed = 115200
upload_port = /dev/cu.usbserial-9552026538
upload_speed = 115200
monitor_port = /dev/cu.usbserial-9552026538
lib_deps =
  m5stack/M5Unified @ ^0.2.7
  m5stack/M5GFX @ ^0.2.15
build_flags =
  -std=gnu++17
  -D CONFIG_MBEDTLS_SSL_MAX_CONTENT_LEN=4096
  -D CONFIG_MBEDTLS_SSL_IN_CONTENT_LEN=4096
  -D CONFIG_MBEDTLS_SSL_OUT_CONTENT_LEN=4096

[env:native]
platform = native
test_framework = unity
build_flags =
  -std=gnu++17
